#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely with "sleep 2" and "I am invincible!!! with a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM 
done
